#!/bin/bash

export LC_ALL=C

#git submodule deinit --all -f
docker run --rm \
    -e LINTER_RULES_PATH=/ \
    -e LOG_LEVEL=NOTICE \
    -e REPORT_OUTPUT_FOLDER=/tmp/megalinter-reports \
    -e RUN_LOCAL=true \
    -e ENABLE=ACTION,DOCKERFILE,JSON,MAKEFILE,MARKDOWN,PYTHON \
    -e DISABLE_LINTERS=PYTHON_PYRIGHT,PYTHON_RUFF,PYTHON_MYPY,PYTHON_BANDIT \
    -e EXCLUDED_DIRECTORIES=models,.venv \
    -e PYTHON_PYLINT_CONFIG_FILE=.pylintrc-ci \
    -e MEGALINTER_FILES_TO_LINT="$(git ls-files | tr '\n' ',')" \
    -w /tmp/lint \
    -v "$(git rev-parse --show-toplevel)":/tmp/lint oxsecurity/megalinter-python:v7
